### ISSUE TITLE
TWE Weapons don't have proper monetary values

### ISSUE THREAD

**Issue by Teacyn** [Teylor-SG/RGE-Bug-Reports#11]
**Describe the bug**
TWE Weapons are all worth an insane amount of septims to buy or sell despite being similar to vanilla weapons. Talked to JD about it, and it seems to have been a simple oversight. This issue is mostly to serve as a reminder for it to be fixed later when JD is recovered.

**Screenshots**
![image](https://user-images.githubusercontent.com/12898157/78159906-37f09080-7411-11ea-97c3-f3c677336ea6.png)

**Comment by jdsmith2816** [comment]
Resolved for v4.0.1 with fixes sent to Total for inclusion in SWE
