### ISSUE TITLE
The Rift ground textures are seemingly broken

### ISSUE THREAD

**Issue by Teacyn** [Teylor-SG/RGE-Bug-Reports#2]
**Describe the bug**
The ground textures for The Rift section of the map seem to be broken, resulting in a weird orange and green clay mess that turns black if you're more than a few feet away.

**To Reproduce**
Go to the Rift

**Expected behavior**
It seems like for some reason the base texture is missing and it's only drawing the normalmap.

**Screenshots**
https://cdn.discordapp.com/attachments/681651975686979613/692138870967500820/unknown.png
https://cdn.discordapp.com/attachments/681651975686979613/692849005666762802/unknown.png

**Additional context**
I actually kind of really like the orange and green tones, it makes the area look very unique, but at the same time it kind of looks awful due to them turning black at any kind of distance.

**Comment by jdsmith2816** [comment]
For now disable the `Landscapes - Cathedral Concept - LODGen Textures` mod in left pane of MO2.

Issue will be closed when v2.0.1 is released

**Comment by jdsmith2816** [comment]
Looks like I don't have the ability to close issues.
