### ISSUE TITLE
Weird placed dead NPC in Dragon Bridge has an insane amount of loot

### ISSUE THREAD

**Issue by Teacyn** [Teylor-SG/RGE-Bug-Reports#9]
**Describe the bug**
There's a placed dead Thane next to an Executioner's Block in Dragon Bridge that has an absolutely absurd amount of valuables and septims on him. The Executioner's Chest next to him also has a TON of valuables in it, and is not considered stealing.

**To Reproduce**
Go to Dragon Bridge and look for the chopping block.

**Expected behavior**
This guy is most likely supposed to be here, but it doesn't make sense they would just leave all these valuables on him and in the chest (also he's not actually beheaded, though that may not be fixable).

**Screenshots**
(I had already looted him here)
https://cdn.discordapp.com/attachments/681651975686979613/692042204176187392/unknown.png
https://cdn.discordapp.com/attachments/681651975686979613/692042308056645762/unknown.png

**Comment by jdsmith2816** [comment]
Fixed.
